export const truncateText = (text, limit = 200, type = 'words') => {
    if (!text) return { text: '', needsTruncation: false };

    if (type === 'words') {
        const words = text.split(/\s+/).filter(word => word.length > 0);
        if (words.length <= limit) return { text, needsTruncation: false };
        return {
            text: words.slice(0, limit).join(' ') + '...',
            needsTruncation: true
        };
    } else {
        // Character-based truncation (alternative)
        if (text.length <= limit) return { text, needsTruncation: false };
        return {
            text: text.slice(0, limit).trim() + '...',
            needsTruncation: true
        };
    }
};

export const SKILL_SUGGESTIONS = [
    "Python",
    "JavaScript",
    "React",
    "Node.js",
    "Java",
    "C++",
    "C#",
    "PHP",
    "Ruby",
    "Go",
    "Swift",
    "Kotlin",
    "TypeScript",
    "HTML",
    "CSS",
    "SQL",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Firebase",
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker",
    "Kubernetes",
    "Git",
    "GitHub",
    "GitLab",
    "Jira",
    "Agile",
    "Scrum",
    "Project Management",
    "Leadership",
    "Communication",
    "Problem Solving",
    "Critical Thinking",
    "Teamwork",
    "Time Management",
    "Data Analysis",
    "Machine Learning",
    "Artificial Intelligence",
    "Deep Learning",
    "Data Science",
    "R",
    "Excel",
    "Tableau",
    "Power BI",
    "Digital Marketing",
    "SEO",
    "Content Writing",
    "Graphic Design",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Figma",
    "UI/UX Design",
    "Product Management",
    "Sales",
    "Customer Service",
    "Public Speaking",
    "Negotiation",
    "Financial Analysis",
    "Accounting",
    "HR Management",
    "Recruiting",
    "Teaching",
    "Research",
    "Writing",
    "Editing",
    "Photography",
    "Video Editing",
    "Programmer",
    "Web Developer",
    "Software Engineer",
    "DevOps Engineer",
    "System Administrator",
    "Network Engineer",
    "Database Administrator",
    "Business Analyst",
    "Marketing Manager",
    "Sales Representative",
    "Project Coordinator",
    "Product Owner",
    "Scrum Master",
    "Quality Assurance",
    "Technical Writing",
    "Cloud Architect",
    "Security Analyst",
    "Data Engineer",
    "ML Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile Developer",
    "iOS Developer",
    "Android Developer",
    "DevOps",
    "CI/CD",
    "Jenkins",
    "Terraform",
    "Ansible",
    "Linux",
    "Windows Server",
    "Networking",
    "Cybersecurity",
    "Penetration Testing",
    "Ethical Hacking",
    "Blockchain",
    "Smart Contracts",
    "Solidity",
    "Rust",
    "Web3",
    "NFT",
    "Cryptocurrency",
];