// utils/mockJobsData.js
export const MockJobs = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    company: 'TechCorp Africa',
    companyLogo: 'https://ui-avatars.com/api/?background=16730F&color=fff&name=TC',
    companySize: '201-500 employees',
    industry: 'Technology',
    location: 'Lagos, Nigeria',
    workMode: 'Remote',
    salary: '₦800,000 - ₦1,200,000 / month',
    salaryMin: 800000,
    salaryMax: 1200000,
    salaryCurrency: 'NGN',
    postedAt: '2026-06-05T10:00:00Z',
    expiresAt: '2026-06-08T10:00:00Z',
    description: 'We are looking for an experienced Frontend Engineer to lead our web development team.',
    responsibilities: [
      'Develop and maintain responsive web applications using React',
      'Collaborate with backend teams to integrate REST APIs',
      'Lead code reviews and mentor junior developers',
      'Optimize applications for maximum speed and scalability',
    ],
    requirements: [
      { skill: 'React', experience: 4, isRequired: true },
      { skill: 'TypeScript', experience: 3, isRequired: true },
      { skill: 'Tailwind CSS', experience: 2, isRequired: true },
    ],
    benefits: [
      { icon: '🏠', title: 'Remote Work', description: 'Work from anywhere' },
      { icon: '💰', title: 'Competitive Salary', description: 'Above market rate' },
    ],
    applicantsCount: 24,
    isActive: true,
    isVerified: true,
    featured: true,
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    applicationDeadline: '2026-06-10T23:59:59Z',
    contactEmail: 'careers@techcorp.africa',
    companyWebsite: 'https://techcorp.africa',
    tags: ['React', 'TypeScript', 'Remote', 'Senior'],
  },
  {
    id: '2',
    title: 'Backend Developer (Node.js)',
    company: 'FinTech Solutions',
    companyLogo: 'https://ui-avatars.com/api/?background=1A3E32&color=fff&name=FS',
    companySize: '50-100 employees',
    industry: 'Finance',
    location: 'Nairobi, Kenya',
    workMode: 'Hybrid',
    salary: 'KES 250,000 - 350,000 / month',
    salaryMin: 250000,
    salaryMax: 350000,
    salaryCurrency: 'KES',
    postedAt: '2026-06-06T09:00:00Z',
    expiresAt: '2026-06-09T09:00:00Z',
    description: 'Join our fintech team to build scalable payment processing systems.',
    responsibilities: [
      'Design and implement RESTful APIs using Node.js',
      'Optimize database queries and schema design',
      'Implement security best practices',
    ],
    requirements: [
      { skill: 'Node.js', experience: 3, isRequired: true },
      { skill: 'PostgreSQL', experience: 3, isRequired: true },
      { skill: 'Redis', experience: 2, isRequired: true },
    ],
    benefits: [
      { icon: '🍽️', title: 'Lunch Provided', description: 'Daily lunch at office' },
    ],
    applicantsCount: 18,
    isActive: true,
    isVerified: true,
    featured: false,
    jobType: 'Full-time',
    experienceLevel: 'Intermediate',
    applicationDeadline: '2026-06-11T23:59:59Z',
    tags: ['Node.js', 'PostgreSQL', 'Fintech'],
  },
  {
    id: '3',
    title: 'Product Designer (UI/UX)',
    company: 'CreativeHub',
    companyLogo: 'https://ui-avatars.com/api/?background=FF6B35&color=fff&name=CH',
    companySize: '20-50 employees',
    industry: 'Marketing',
    location: 'Accra, Ghana',
    workMode: 'Remote',
    salary: 'GHS 12,000 - 18,000 / month',
    salaryMin: 12000,
    salaryMax: 18000,
    salaryCurrency: 'GHS',
    postedAt: '2026-06-04T14:00:00Z',
    expiresAt: '2026-06-07T14:00:00Z',
    description: 'Seeking a creative Product Designer to shape user experiences.',
    responsibilities: [
      'Lead UX research and usability testing',
      'Create user flows and interactive prototypes',
      'Collaborate with developers',
    ],
    requirements: [
      { skill: 'Figma', experience: 3, isRequired: true },
      { skill: 'User Research', experience: 2, isRequired: true },
    ],
    benefits: [
      { icon: '🎨', title: 'Creative Freedom', description: 'Own your designs' },
    ],
    applicantsCount: 42,
    isActive: true,
    isVerified: true,
    featured: true,
    jobType: 'Full-time',
    experienceLevel: 'Intermediate',
    applicationDeadline: '2026-06-10T23:59:59Z',
    tags: ['Figma', 'UI/UX', 'Design'],
  },
  {
    id: '4',
    title: 'DevOps Engineer',
    company: 'CloudNative Inc',
    companyLogo: 'https://ui-avatars.com/api/?background=7C3AED&color=fff&name=CN',
    companySize: '100-200 employees',
    industry: 'Technology',
    location: 'Cape Town, South Africa',
    workMode: 'Remote',
    salary: 'ZAR 80,000 - 120,000 / month',
    salaryMin: 80000,
    salaryMax: 120000,
    salaryCurrency: 'ZAR',
    postedAt: '2026-06-03T11:00:00Z',
    expiresAt: '2026-06-06T11:00:00Z',
    description: 'Looking for a DevOps engineer to manage our cloud infrastructure.',
    responsibilities: [
      'Manage AWS infrastructure',
      'Implement CI/CD pipelines',
      'Monitor system performance',
    ],
    requirements: [
      { skill: 'AWS', experience: 3, isRequired: true },
      { skill: 'Docker', experience: 2, isRequired: true },
      { skill: 'Kubernetes', experience: 2, isRequired: false },
    ],
    benefits: [
      { icon: '☁️', title: 'Cloud Budget', description: 'Learning resources' },
    ],
    applicantsCount: 15,
    isActive: true,
    isVerified: true,
    featured: false,
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    applicationDeadline: '2026-06-09T23:59:59Z',
    tags: ['AWS', 'Docker', 'Kubernetes'],
  },
  {
    id: '5',
    title: 'Data Scientist',
    company: 'DataDrive AI',
    companyLogo: 'https://ui-avatars.com/api/?background=DC2626&color=fff&name=DA',
    companySize: '50-100 employees',
    industry: 'Technology',
    location: 'Lagos, Nigeria',
    workMode: 'Onsite',
    salary: '₦1,000,000 - 1,500,000 / month',
    salaryMin: 1000000,
    salaryMax: 1500000,
    salaryCurrency: 'NGN',
    postedAt: '2026-06-02T09:00:00Z',
    expiresAt: '2026-06-05T09:00:00Z',
    description: 'Join our AI team to build machine learning models.',
    responsibilities: [
      'Develop ML models',
      'Analyze large datasets',
      'Collaborate with engineering team',
    ],
    requirements: [
      { skill: 'Python', experience: 4, isRequired: true },
      { skill: 'Machine Learning', experience: 3, isRequired: true },
      { skill: 'TensorFlow', experience: 2, isRequired: true },
    ],
    benefits: [
      { icon: '🤖', title: 'AI Resources', description: 'Access to GPUs' },
    ],
    applicantsCount: 31,
    isActive: true,
    isVerified: false,
    featured: false,
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    applicationDeadline: '2026-06-08T23:59:59Z',
    tags: ['Python', 'ML', 'AI'],
  },
  {
    id: '6',
    title: 'Marketing Manager',
    company: 'BrandBoost',
    companyLogo: 'https://ui-avatars.com/api/?background=0891B2&color=fff&name=BB',
    companySize: '20-50 employees',
    industry: 'Marketing',
    location: 'Nairobi, Kenya',
    workMode: 'Hybrid',
    salary: 'KES 200,000 - 300,000 / month',
    salaryMin: 200000,
    salaryMax: 300000,
    salaryCurrency: 'KES',
    postedAt: '2026-06-05T14:00:00Z',
    expiresAt: '2026-06-08T14:00:00Z',
    description: 'Lead our marketing team and drive brand growth.',
    responsibilities: [
      'Develop marketing strategies',
      'Manage social media campaigns',
      'Analyze market trends',
    ],
    requirements: [
      { skill: 'Digital Marketing', experience: 4, isRequired: true },
      { skill: 'SEO', experience: 3, isRequired: true },
    ],
    benefits: [
      { icon: '📈', title: 'Growth Bonus', description: 'Performance based' },
    ],
    applicantsCount: 12,
    isActive: true,
    isVerified: true,
    featured: false,
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    applicationDeadline: '2026-06-11T23:59:59Z',
    tags: ['Marketing', 'SEO', 'Social Media'],
  },
  {
    id: '7',
    title: 'Intern Frontend Developer',
    company: 'TechStart',
    companyLogo: 'https://ui-avatars.com/api/?background=65A30D&color=fff&name=TS',
    companySize: '10-20 employees',
    industry: 'Technology',
    location: 'Accra, Ghana',
    workMode: 'Remote',
    salary: 'GHS 3,000 - 5,000 / month',
    salaryMin: 3000,
    salaryMax: 5000,
    salaryCurrency: 'GHS',
    postedAt: '2026-06-06T10:00:00Z',
    expiresAt: '2026-06-09T10:00:00Z',
    description: 'Kickstart your career as a frontend developer intern.',
    responsibilities: [
      'Build UI components',
      'Learn modern frameworks',
      'Work with senior developers',
    ],
    requirements: [
      { skill: 'HTML/CSS', experience: 0, isRequired: true },
      { skill: 'JavaScript', experience: 0, isRequired: true },
      { skill: 'React', experience: 0, isRequired: false },
    ],
    benefits: [
      { icon: '📚', title: 'Mentorship', description: 'Learn from experts' },
    ],
    applicantsCount: 56,
    isActive: true,
    isVerified: true,
    featured: false,
    jobType: 'Internship',
    experienceLevel: 'Entry',
    applicationDeadline: '2026-06-12T23:59:59Z',
    tags: ['HTML', 'CSS', 'JavaScript', 'Internship'],
  },
  {
    id: '8',
    title: 'Part-time QA Tester',
    company: 'SoftQuality',
    companyLogo: 'https://ui-avatars.com/api/?background=9333EA&color=fff&name=SQ',
    companySize: '20-50 employees',
    industry: 'Technology',
    location: 'Lagos, Nigeria',
    workMode: 'Remote',
    salary: '₦200,000 - 300,000 / month',
    salaryMin: 200000,
    salaryMax: 300000,
    salaryCurrency: 'NGN',
    postedAt: '2026-06-04T08:00:00Z',
    expiresAt: '2026-06-07T08:00:00Z',
    description: 'Looking for a part-time QA tester for our web applications.',
    responsibilities: [
      'Write test cases',
      'Perform manual testing',
      'Report bugs',
    ],
    requirements: [
      { skill: 'Testing', experience: 2, isRequired: true },
      { skill: 'Cypress', experience: 1, isRequired: false },
    ],
    benefits: [
      { icon: '⏰', title: 'Flexible Hours', description: 'Work part-time' },
    ],
    applicantsCount: 8,
    isActive: true,
    isVerified: false,
    featured: false,
    jobType: 'Part-time',
    experienceLevel: 'Entry',
    applicationDeadline: '2026-06-10T23:59:59Z',
    tags: ['QA', 'Testing', 'Part-time'],
  },
];


export const INITIAL_EXERCISES = [
  {
    id: "rec-1",
    title: "Senior Backend Engineer — Q3 Expansion",
    position: "Backend Engineer",
    department: "Engineering",
    activeStage: "Stage 2: Tech Interview",
    invited: 42,
    accepted: 29,
    declined: 6,
    passed: 17,
    failed: 9,
    hired: 3,
    status: "Open",
    lastUpdated: "10 mins ago",
    createdDate: "2026-07-01",
    description:
      "Lead architecture and microservices design for Bejite enterprise.",
    pipeline: [
      { id: 1, step: "01", name: "Screening", title: "Invited", count: 29 },
      {
        id: 2,
        step: "02",
        name: "Tech Interview",
        title: "Invited",
        count: 17,
      },
      { id: 3, step: "03", name: "Final Offer", title: "Invited", count: 13 },
    ],
    stagesList: [
      {
        id: 1,
        name: "Accepted",
        description: "Candidate confirmed availability",
        interviewer: "Recruiter Screening",
        duration: "30 mins",
        count: 0,
        status: "Complete",
      },
      {
        id: 2,
        name: "Technical Assessment",
        description: "System design & coding evaluation",
        interviewer: "Lead Architect",
        duration: "60 mins",
        count: 1,
        status: "Active",
      },
      {
        id: 3,
        name: "Invited",
        description: "Invitation sent via email",
        interviewer: "Bejite Team",
        duration: "15 mins",
        count: 1,
        status: "Not Started",
      },
    ],
    candidates: [
      {
        id: "cand-1",
        userId: "user-101",
        name: "Amina Yusuf",
        email: "david.ogunleye@gmail.com",
        phone: "+234 802 345 6789",
        avatar:
          "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
        currentStage: "Invited",
        outcome: "Pending",
      },
      {
        id: "cand-2",
        userId: "user-102",
        name: "Daniel Osie",
        email: "david.ogunleye@gmail.com",
        phone: "+234 802 345 6789",
        avatar:
          "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        currentStage: "Invited",
        outcome: "Pending",
      },
      {
        id: "cand-3",
        userId: "user-103",
        name: "Grace Mwangi",
        email: "david.ogunleye@gmail.com",
        phone: "+234 802 345 6789",
        avatar:
          "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
        currentStage: "Invited",
        outcome: "Pending",
      },
    ],
  },
  {
    id: "rec-2",
    title: "Product Designer Intake",
    position: "Product Designer",
    department: "Product & Design",
    activeStage: "Stage 1: Screening",
    invited: 18,
    accepted: 11,
    declined: 3,
    passed: 8,
    failed: 3,
    hired: 1,
    status: "Open",
    lastUpdated: "20 mins ago",
    createdDate: "2026-07-05",
    description:
      "Design intuitive UI/UX components and design system patterns.",
    pipeline: [
      { id: 1, step: "01", name: "Screening", title: "Invited", count: 11 },
      {
        id: 2,
        step: "02",
        name: "Design Challenge",
        title: "Invited",
        count: 5,
      },
    ],
    stagesList: [
      {
        id: 1,
        name: "Screening",
        description: "Initial portfolio & resume review",
        interviewer: "Design Lead",
        duration: "30 mins",
        count: 11,
        status: "Active",
      },
      {
        id: 2,
        name: "Design Challenge",
        description: "Interactive Figma prototype evaluation",
        interviewer: "Product Team",
        duration: "90 mins",
        count: 5,
        status: "Not Started",
      },
    ],
    candidates: [],
  },
  {
    id: "rec-3",
    title: "Ops Associate Batch 4",
    position: "Ops Associate",
    department: "Operations",
    activeStage: "Final: Offer",
    invited: 35,
    accepted: 24,
    declined: 9,
    passed: 15,
    failed: 9,
    hired: 4,
    status: "Final Stage",
    lastUpdated: "30 mins ago",
    createdDate: "2026-06-28",
    description: "Coordinate enterprise logistics and partner operations.",
    pipeline: [
      { id: 1, step: "01", name: "Screening", title: "Invited", count: 24 },
      { id: 2, step: "02", name: "Final Offer", title: "Invited", count: 15 },
    ],
    stagesList: [
      {
        id: 1,
        name: "Ops Interview",
        description: "Logistics and scenario handling",
        interviewer: "Ops Manager",
        duration: "45 mins",
        count: 15,
        status: "Complete",
      },
    ],
    candidates: [],
  },
  {
    id: "rec-4",
    title: "Senior Data Analyst",
    position: "Data Data Analyst",
    department: "Data Analytics",
    activeStage: "Hired",
    invited: 33,
    accepted: 12,
    declined: 4,
    passed: 12,
    failed: 0,
    hired: 3,
    status: "Closed",
    lastUpdated: "45 mins ago",
    createdDate: "2026-06-15",
    description: "Perform data modeling, dashboards, and growth analytics.",
    pipeline: [
      { id: 1, step: "01", name: "Screening", title: "Invited", count: 12 },
    ],
    stagesList: [
      {
        id: 1,
        name: "SQL & Analytics Test",
        description: "Database queries and data modeling test",
        interviewer: "Data Team Lead",
        duration: "60 mins",
        count: 3,
        status: "Complete",
      },
    ],
    candidates: [],
  },
];

export const INITIAL_BIRTHDAY_DATA = [
  {
    id: "b1",
    name: "Sarah Jenkins",
    role: "Lead UX Designer at Designify",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    birthday: "Today",
    dateFormatted: "August 10",
    category: "today",
    hasVerifiedBadge: true,
    mutualCount: 14,
    wished: false,
  },
  {
    id: "b2",
    name: "David Chen",
    role: "Senior Frontend Engineer at TechCorp",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    birthday: "Today",
    dateFormatted: "August 10",
    category: "today",
    hasVerifiedBadge: false,
    mutualCount: 8,
    wished: false,
  },
  {
    id: "b3",
    name: "Amara Okafor",
    role: "Talent Acquisition Specialist at Bejite",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    birthday: "Tomorrow",
    dateFormatted: "August 11",
    category: "upcoming",
    hasVerifiedBadge: true,
    mutualCount: 22,
    wished: false,
  },
  {
    id: "b4",
    name: "Marcus Vance",
    role: "Product Manager at Stripe",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    birthday: "In 3 days",
    dateFormatted: "August 13",
    category: "upcoming",
    hasVerifiedBadge: false,
    mutualCount: 5,
    wished: false,
  },
  {
    id: "b5",
    name: "Elena Rostova",
    role: "VP of Engineering at CloudScale",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    birthday: "In 5 days",
    dateFormatted: "August 15",
    category: "upcoming",
    hasVerifiedBadge: true,
    mutualCount: 31,
    wished: false,
  },
  {
    id: "b6",
    name: "Michael Scott",
    role: "Regional Director at Dunder Mifflin",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    birthday: "In 6 days",
    dateFormatted: "August 16",
    category: "upcoming",
    hasVerifiedBadge: false,
    mutualCount: 19,
    wished: false,
  },
  {
    id: "b7",
    name: "Priya Sharma",
    role: "Lead Data Scientist at BioAI",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    birthday: "In 8 days",
    dateFormatted: "August 18",
    category: "upcoming",
    hasVerifiedBadge: true,
    mutualCount: 12,
    wished: false,
  },
  {
    id: "b8",
    name: "James Wilson",
    role: "Marketing Director at Innovate",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    birthday: "In 10 days",
    dateFormatted: "August 20",
    category: "upcoming",
    hasVerifiedBadge: false,
    mutualCount: 7,
    wished: false,
  },
  {
    id: "b9",
    name: "Fatima Zahra",
    role: "Full Stack Developer at DevHub",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    birthday: "In 12 days",
    dateFormatted: "August 22",
    category: "upcoming",
    hasVerifiedBadge: true,
    mutualCount: 18,
    wished: false,
  },
  {
    id: "b10",
    name: "Anita Patel",
    role: "HR Business Partner at PeopleFirst",
    image: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    birthday: "Yesterday",
    dateFormatted: "August 9",
    category: "recent",
    hasVerifiedBadge: false,
    mutualCount: 11,
    wished: false,
  },
  {
    id: "b11",
    name: "Kevin Zhang",
    role: "DevOps Engineer at InfraCloud",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    birthday: "3 days ago",
    dateFormatted: "August 7",
    category: "recent",
    hasVerifiedBadge: true,
    mutualCount: 9,
    wished: false,
  },
  {
    id: "b12",
    name: "Blessing Chukwu",
    role: "Content Strategist at MediaPulse",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80",
    birthday: "5 days ago",
    dateFormatted: "August 5",
    category: "recent",
    hasVerifiedBadge: false,
    mutualCount: 16,
    wished: false,
  },
  {
    id: "b13",
    name: "Alex Rivera",
    role: "Cybersecurity Specialist at CyberShield",
    image: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    birthday: "1 week ago",
    dateFormatted: "August 3",
    category: "recent",
    hasVerifiedBadge: true,
    mutualCount: 15,
    wished: false,
  },
];

export const PRESET_WISHES = [
  "🎂 Happy Birthday! Wishing you a fantastic day and great success ahead! 🎉",
  "🎈 Wishing you a wonderful birthday filled with joy and celebration! 🌟",
  "🎂 Happy Birthday! Hope to catch up soon!",
  "🎁 Have a brilliant birthday and a fantastic year ahead! 🚀",
];
