// utils/mockJobsData.js
export const MockJobs = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    company: 'TechCorp Africa',
    companyLogo: 'https://ui-avatars.com/api/?background=16730F&color=fff&name=TC',
    companySize: '201-500 employees',
    industry: 'Technology',
    location: 'Lagos, Nigeria',
    workMode: 'Remote',
    salary: '₦800,000 - ₦1,200,000 / month',
    salaryMin: 800000,
    salaryMax: 1200000,
    salaryCurrency: 'NGN',
    postedAt: '2026-06-05T10:00:00Z',
    expiresAt: '2026-06-08T10:00:00Z',
    description: 'We are looking for an experienced Frontend Engineer to lead our web development team.',
    responsibilities: [
      'Develop and maintain responsive web applications using React',
      'Collaborate with backend teams to integrate REST APIs',
      'Lead code reviews and mentor junior developers',
      'Optimize applications for maximum speed and scalability',
    ],
    requirements: [
      { skill: 'React', experience: 4, isRequired: true },
      { skill: 'TypeScript', experience: 3, isRequired: true },
      { skill: 'Tailwind CSS', experience: 2, isRequired: true },
    ],
    benefits: [
      { icon: '🏠', title: 'Remote Work', description: 'Work from anywhere' },
      { icon: '💰', title: 'Competitive Salary', description: 'Above market rate' },
    ],
    applicantsCount: 24,
    isActive: true,
    isVerified: true,
    featured: true,
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    applicationDeadline: '2026-06-10T23:59:59Z',
    contactEmail: 'careers@techcorp.africa',
    companyWebsite: 'https://techcorp.africa',
    tags: ['React', 'TypeScript', 'Remote', 'Senior'],
  },
  {
    id: '2',
    title: 'Backend Developer (Node.js)',
    company: 'FinTech Solutions',
    companyLogo: 'https://ui-avatars.com/api/?background=1A3E32&color=fff&name=FS',
    companySize: '50-100 employees',
    industry: 'Finance',
    location: 'Nairobi, Kenya',
    workMode: 'Hybrid',
    salary: 'KES 250,000 - 350,000 / month',
    salaryMin: 250000,
    salaryMax: 350000,
    salaryCurrency: 'KES',
    postedAt: '2026-06-06T09:00:00Z',
    expiresAt: '2026-06-09T09:00:00Z',
    description: 'Join our fintech team to build scalable payment processing systems.',
    responsibilities: [
      'Design and implement RESTful APIs using Node.js',
      'Optimize database queries and schema design',
      'Implement security best practices',
    ],
    requirements: [
      { skill: 'Node.js', experience: 3, isRequired: true },
      { skill: 'PostgreSQL', experience: 3, isRequired: true },
      { skill: 'Redis', experience: 2, isRequired: true },
    ],
    benefits: [
      { icon: '🍽️', title: 'Lunch Provided', description: 'Daily lunch at office' },
    ],
    applicantsCount: 18,
    isActive: true,
    isVerified: true,
    featured: false,
    jobType: 'Full-time',
    experienceLevel: 'Intermediate',
    applicationDeadline: '2026-06-11T23:59:59Z',
    tags: ['Node.js', 'PostgreSQL', 'Fintech'],
  },
  {
    id: '3',
    title: 'Product Designer (UI/UX)',
    company: 'CreativeHub',
    companyLogo: 'https://ui-avatars.com/api/?background=FF6B35&color=fff&name=CH',
    companySize: '20-50 employees',
    industry: 'Marketing',
    location: 'Accra, Ghana',
    workMode: 'Remote',
    salary: 'GHS 12,000 - 18,000 / month',
    salaryMin: 12000,
    salaryMax: 18000,
    salaryCurrency: 'GHS',
    postedAt: '2026-06-04T14:00:00Z',
    expiresAt: '2026-06-07T14:00:00Z',
    description: 'Seeking a creative Product Designer to shape user experiences.',
    responsibilities: [
      'Lead UX research and usability testing',
      'Create user flows and interactive prototypes',
      'Collaborate with developers',
    ],
    requirements: [
      { skill: 'Figma', experience: 3, isRequired: true },
      { skill: 'User Research', experience: 2, isRequired: true },
    ],
    benefits: [
      { icon: '🎨', title: 'Creative Freedom', description: 'Own your designs' },
    ],
    applicantsCount: 42,
    isActive: true,
    isVerified: true,
    featured: true,
    jobType: 'Full-time',
    experienceLevel: 'Intermediate',
    applicationDeadline: '2026-06-10T23:59:59Z',
    tags: ['Figma', 'UI/UX', 'Design'],
  },
  {
    id: '4',
    title: 'DevOps Engineer',
    company: 'CloudNative Inc',
    companyLogo: 'https://ui-avatars.com/api/?background=7C3AED&color=fff&name=CN',
    companySize: '100-200 employees',
    industry: 'Technology',
    location: 'Cape Town, South Africa',
    workMode: 'Remote',
    salary: 'ZAR 80,000 - 120,000 / month',
    salaryMin: 80000,
    salaryMax: 120000,
    salaryCurrency: 'ZAR',
    postedAt: '2026-06-03T11:00:00Z',
    expiresAt: '2026-06-06T11:00:00Z',
    description: 'Looking for a DevOps engineer to manage our cloud infrastructure.',
    responsibilities: [
      'Manage AWS infrastructure',
      'Implement CI/CD pipelines',
      'Monitor system performance',
    ],
    requirements: [
      { skill: 'AWS', experience: 3, isRequired: true },
      { skill: 'Docker', experience: 2, isRequired: true },
      { skill: 'Kubernetes', experience: 2, isRequired: false },
    ],
    benefits: [
      { icon: '☁️', title: 'Cloud Budget', description: 'Learning resources' },
    ],
    applicantsCount: 15,
    isActive: true,
    isVerified: true,
    featured: false,
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    applicationDeadline: '2026-06-09T23:59:59Z',
    tags: ['AWS', 'Docker', 'Kubernetes'],
  },
  {
    id: '5',
    title: 'Data Scientist',
    company: 'DataDrive AI',
    companyLogo: 'https://ui-avatars.com/api/?background=DC2626&color=fff&name=DA',
    companySize: '50-100 employees',
    industry: 'Technology',
    location: 'Lagos, Nigeria',
    workMode: 'Onsite',
    salary: '₦1,000,000 - 1,500,000 / month',
    salaryMin: 1000000,
    salaryMax: 1500000,
    salaryCurrency: 'NGN',
    postedAt: '2026-06-02T09:00:00Z',
    expiresAt: '2026-06-05T09:00:00Z',
    description: 'Join our AI team to build machine learning models.',
    responsibilities: [
      'Develop ML models',
      'Analyze large datasets',
      'Collaborate with engineering team',
    ],
    requirements: [
      { skill: 'Python', experience: 4, isRequired: true },
      { skill: 'Machine Learning', experience: 3, isRequired: true },
      { skill: 'TensorFlow', experience: 2, isRequired: true },
    ],
    benefits: [
      { icon: '🤖', title: 'AI Resources', description: 'Access to GPUs' },
    ],
    applicantsCount: 31,
    isActive: true,
    isVerified: false,
    featured: false,
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    applicationDeadline: '2026-06-08T23:59:59Z',
    tags: ['Python', 'ML', 'AI'],
  },
  {
    id: '6',
    title: 'Marketing Manager',
    company: 'BrandBoost',
    companyLogo: 'https://ui-avatars.com/api/?background=0891B2&color=fff&name=BB',
    companySize: '20-50 employees',
    industry: 'Marketing',
    location: 'Nairobi, Kenya',
    workMode: 'Hybrid',
    salary: 'KES 200,000 - 300,000 / month',
    salaryMin: 200000,
    salaryMax: 300000,
    salaryCurrency: 'KES',
    postedAt: '2026-06-05T14:00:00Z',
    expiresAt: '2026-06-08T14:00:00Z',
    description: 'Lead our marketing team and drive brand growth.',
    responsibilities: [
      'Develop marketing strategies',
      'Manage social media campaigns',
      'Analyze market trends',
    ],
    requirements: [
      { skill: 'Digital Marketing', experience: 4, isRequired: true },
      { skill: 'SEO', experience: 3, isRequired: true },
    ],
    benefits: [
      { icon: '📈', title: 'Growth Bonus', description: 'Performance based' },
    ],
    applicantsCount: 12,
    isActive: true,
    isVerified: true,
    featured: false,
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    applicationDeadline: '2026-06-11T23:59:59Z',
    tags: ['Marketing', 'SEO', 'Social Media'],
  },
  {
    id: '7',
    title: 'Intern Frontend Developer',
    company: 'TechStart',
    companyLogo: 'https://ui-avatars.com/api/?background=65A30D&color=fff&name=TS',
    companySize: '10-20 employees',
    industry: 'Technology',
    location: 'Accra, Ghana',
    workMode: 'Remote',
    salary: 'GHS 3,000 - 5,000 / month',
    salaryMin: 3000,
    salaryMax: 5000,
    salaryCurrency: 'GHS',
    postedAt: '2026-06-06T10:00:00Z',
    expiresAt: '2026-06-09T10:00:00Z',
    description: 'Kickstart your career as a frontend developer intern.',
    responsibilities: [
      'Build UI components',
      'Learn modern frameworks',
      'Work with senior developers',
    ],
    requirements: [
      { skill: 'HTML/CSS', experience: 0, isRequired: true },
      { skill: 'JavaScript', experience: 0, isRequired: true },
      { skill: 'React', experience: 0, isRequired: false },
    ],
    benefits: [
      { icon: '📚', title: 'Mentorship', description: 'Learn from experts' },
    ],
    applicantsCount: 56,
    isActive: true,
    isVerified: true,
    featured: false,
    jobType: 'Internship',
    experienceLevel: 'Entry',
    applicationDeadline: '2026-06-12T23:59:59Z',
    tags: ['HTML', 'CSS', 'JavaScript', 'Internship'],
  },
  {
    id: '8',
    title: 'Part-time QA Tester',
    company: 'SoftQuality',
    companyLogo: 'https://ui-avatars.com/api/?background=9333EA&color=fff&name=SQ',
    companySize: '20-50 employees',
    industry: 'Technology',
    location: 'Lagos, Nigeria',
    workMode: 'Remote',
    salary: '₦200,000 - 300,000 / month',
    salaryMin: 200000,
    salaryMax: 300000,
    salaryCurrency: 'NGN',
    postedAt: '2026-06-04T08:00:00Z',
    expiresAt: '2026-06-07T08:00:00Z',
    description: 'Looking for a part-time QA tester for our web applications.',
    responsibilities: [
      'Write test cases',
      'Perform manual testing',
      'Report bugs',
    ],
    requirements: [
      { skill: 'Testing', experience: 2, isRequired: true },
      { skill: 'Cypress', experience: 1, isRequired: false },
    ],
    benefits: [
      { icon: '⏰', title: 'Flexible Hours', description: 'Work part-time' },
    ],
    applicantsCount: 8,
    isActive: true,
    isVerified: false,
    featured: false,
    jobType: 'Part-time',
    experienceLevel: 'Entry',
    applicationDeadline: '2026-06-10T23:59:59Z',
    tags: ['QA', 'Testing', 'Part-time'],
  },
];